{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Fact - Rota\",\"Fact - Care Hires Data\",\"Dim - Site Master\",\"Dim - Date\",\"Measures_Table\",\"Fact - Timesheet-updated\",\"Fact - Timesheets\",\"MISC - Care Hires Key\",\"MISC - Rota Key\",\"Data_Source\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.137.1102.0 (24.10)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-GB",
    "cultures": [
      {
        "name": "en-GB",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Fact - Timesheets",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Folder.Files(Data_Source),",
          "    #\"C:\\Users\\kporw\\Desktop\\PORTFOLIO\\Care Hours - Data\\_Fact - Timesheets csv\" = Source{[#\"Folder Path\"=\"C:\\Users\\kporw\\Desktop\\PORTFOLIO\\Care Hours - Data\\\",Name=\"Fact - Timesheets.csv\"]}[Content],",
          "    #\"Imported CSV\" = Csv.Document(#\"C:\\Users\\kporw\\Desktop\\PORTFOLIO\\Care Hours - Data\\_Fact - Timesheets csv\",[Delimiter=\",\", Columns=18, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars=true]),",
          "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Promoted Headers\",{\"Department\", \"Job\", \"Hours\", \"Other\", \"Commissioned Hours\", \"Service ID\", \"Employee_Number\", \"Employee_Name\", \"Pay_Date\", \"Time_in\", \"Time Out\", \"Authorised_by_Manager\", \"Authorised_by_Employee\", \"Pay_Code\", \"Pay_Category\", \"Location_Short\"}),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Other Columns1\",{{\"Commissioned Hours\", type number}, {\"Hours\", type number}, {\"Other\", type number}, {\"Pay_Date\", type date}}),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type\", each true),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Filtered Rows\",{{\"Time_in\", type time}, {\"Time Out\", type time}}),",
          "    #\"Filtered Rows1\" = Table.SelectRows(#\"Changed Type1\", each true)",
          "in",
          "    #\"Filtered Rows1\""
        ],
        "kind": "m",
        "lineageTag": "a09ee4ed-e357-47e7-8eca-f91d45fdeadf",
        "queryGroup": "Disabled_Load"
      },
      {
        "name": "MISC - Care Hires Key",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Folder.Files(Data_Source),",
          "    #\"C:\\Users\\kporw\\Desktop\\PORTFOLIO\\Care Hours - Data\\_MISC - Care Hires Key csv\" = Source{[#\"Folder Path\"=\"C:\\Users\\kporw\\Desktop\\PORTFOLIO\\Care Hours - Data\\\",Name=\"MISC - Care Hires Key.csv\"]}[Content],",
          "    #\"Imported CSV\" = Csv.Document(#\"C:\\Users\\kporw\\Desktop\\PORTFOLIO\\Care Hours - Data\\_MISC - Care Hires Key csv\",[Delimiter=\",\", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Service ID\", Int64.Type}, {\"Service_Short\", type text}, {\"Site_Name\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "83895404-5c38-4626-bec1-31a8f032d0d3",
        "queryGroup": "Disabled_Load"
      },
      {
        "name": "MISC - Rota Key",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Folder.Files(Data_Source),",
          "    #\"C:\\Users\\kporw\\Desktop\\PORTFOLIO\\Care Hours - Data\\_MISC - Rota Key csv\" = Source{[#\"Folder Path\"=\"C:\\Users\\kporw\\Desktop\\PORTFOLIO\\Care Hours - Data\\\",Name=\"MISC - Rota Key.csv\"]}[Content],",
          "    #\"Imported CSV\" = Csv.Document(#\"C:\\Users\\kporw\\Desktop\\PORTFOLIO\\Care Hours - Data\\_MISC - Rota Key csv\",[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Service_Short\", type text}, {\"Service\", type text}, {\"Region\", type text}, {\"City\", type text}, {\"Service ID\", Int64.Type}}),",
          "    #\"Removed Duplicates\" = Table.Distinct(#\"Changed Type\", {\"Service ID\"}),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Removed Duplicates\",{{\"Service ID\", type text}})",
          "in",
          "    #\"Changed Type1\""
        ],
        "kind": "m",
        "lineageTag": "af115f10-162e-4858-9587-e65e9d75c784",
        "queryGroup": "Disabled_Load"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Disabled_Load"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Parameters"
      }
    ],
    "relationships": [
      {
        "name": "AutoDetected_3d8e8b69-ef7a-44c9-936f-af0ea76167d7",
        "fromColumn": "Service ID",
        "fromTable": "Fact - Care Hires Data",
        "toColumn": "Service ID",
        "toTable": "Dim - Site Master"
      },
      {
        "name": "fa5bf0b0-0a14-8886-60bf-59bbd72b6ed9",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Week Ending",
        "fromTable": "Fact - Rota",
        "toCardinality": "many",
        "toColumn": "End of Week",
        "toTable": "Dim - Date"
      },
      {
        "name": "1ffc2bc0-826e-8391-5430-97dc9252688f",
        "fromColumn": "Service ID",
        "fromTable": "Fact - Rota",
        "toColumn": "Service ID",
        "toTable": "Dim - Site Master"
      },
      {
        "name": "d141c07b-a4f6-0bb7-ee79-d7a04f49f84c",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Job_StartDate",
        "fromTable": "Fact - Care Hires Data",
        "toColumn": "Date",
        "toTable": "Dim - Date"
      },
      {
        "name": "c4488daf-4f30-b2aa-1a86-41f65f678409",
        "fromColumn": "Pay_Date",
        "fromTable": "Fact - Timesheet-updated",
        "toColumn": "Date",
        "toTable": "Dim - Date"
      },
      {
        "name": "e3caf5e1-7aff-acef-0f47-1feeba2a625d",
        "fromColumn": "Service ID",
        "fromTable": "Fact - Timesheet-updated",
        "toColumn": "Service ID",
        "toTable": "Dim - Site Master"
      }
    ],
    "sourceQueryCulture": "en-GB",
    "tables": [
      {
        "name": "Fact - Rota",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Site_Short",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "51fe48a1-57fb-42c6-ad19-2275f611ca7f",
            "sourceColumn": "Site_Short",
            "summarizeBy": "none"
          },
          {
            "name": "SU Hours",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "b82c98ca-02d0-4792-a04e-eaffd3035a14",
            "sourceColumn": "SU Hours",
            "summarizeBy": "sum"
          },
          {
            "name": "Week Ending",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              },
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "3c6c25ff-ead0-4aac-a557-39275a47e677",
            "sourceColumn": "Week Ending",
            "summarizeBy": "none"
          },
          {
            "name": "Service ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "57f2e6cc-1ace-4059-8cff-75d805d5395a",
            "sourceColumn": "Service ID",
            "summarizeBy": "none"
          },
          {
            "name": "SU_Hours_per_day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "5b91744a-f6ed-4825-926a-96659b32c593",
            "sourceColumn": "SU_Hours_per_day",
            "summarizeBy": "sum"
          },
          {
            "name": "Site_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ee460468-e1d7-4289-a79b-47ea847ee9e6",
            "sourceColumn": "Site_Name",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c81b1c8d-3633-4b54-add4-49a3d2a07882",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Service_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "96152ab3-2664-4c98-9f1a-3ac6d0e9fdbb",
            "sourceColumn": "Service_type",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "949570f3-9423-47a9-8048-d9a62d82bc6b",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "Contracted_Hours_daily",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "CALCULATE( SUM('Fact - Rota'[SU_Hours_per_day]))",
            "isDataTypeInferred": true,
            "lineageTag": "5e366456-e735-4e0c-8386-52f01f886f04",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "9518420b-ec27-42d1-97aa-9701a4da6692",
        "partitions": [
          {
            "name": "Fact - Rota",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "Source = Folder.Files(Data_Source),",
                "    #\"C:\\Users\\kporw\\Desktop\\PORTFOLIO\\Care Hours - Data\\_Fact - Rota xlsx\" = Source{[#\"Folder Path\"=\"C:\\Users\\kporw\\Desktop\\PORTFOLIO\\Care Hours - Data\\\",Name=\"Fact - Rota.xlsx\"]}[Content],",
                "    #\"Imported Excel Workbook\" = Excel.Workbook(#\"C:\\Users\\kporw\\Desktop\\PORTFOLIO\\Care Hours - Data\\_Fact - Rota xlsx\"),",
                "    #\"FACT - Rota_Sheet\" = #\"Imported Excel Workbook\"{[Item=\"FACT - Rota\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"FACT - Rota_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"SU Hours\", type number}, {\"SU_Hours_per_day\", type number}, {\"Service ID\", type text}}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Changed Type\", {\"Service ID\"}, #\"Dim - Site Master\", {\"Service ID\"}, \"Dim - Site Master\", JoinKind.LeftOuter),",
                "    #\"Expanded Dim - Site Master\" = Table.ExpandTableColumn(#\"Merged Queries\", \"Dim - Site Master\", {\"Region\", \"Service_type\", \"City\"}, {\"Region\", \"Service_type\", \"City\"})",
                "in",
                "    #\"Expanded Dim - Site Master\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact - Care Hires Data",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4c6925a1-5179-4c0f-b901-73780175f3fc",
            "sourceColumn": "Id",
            "summarizeBy": "count"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "95bfc33f-5a9d-4f4e-bb2a-1d0903d503c5",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          },
          {
            "name": "Agency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b16c0cff-6d40-43d8-bfdb-1bab83632307",
            "sourceColumn": "Agency",
            "summarizeBy": "none"
          },
          {
            "name": "Site_Short",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f79fb0db-95b0-4053-96df-da67a7a6853d",
            "sourceColumn": "Site_Short",
            "summarizeBy": "none"
          },
          {
            "name": "WorkerType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "58e9d6f7-66cd-426f-9351-3b5e17718fd9",
            "sourceColumn": "WorkerType",
            "summarizeBy": "none"
          },
          {
            "name": "EstimatedHours",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ee1bc3d3-0fbd-4cb2-a5c4-08c3ddf5040b",
            "sourceColumn": "EstimatedHours",
            "summarizeBy": "sum"
          },
          {
            "name": "EstimatedBilled",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1765e97d-efb8-468a-81bf-6e94c8efdeca",
            "sourceColumn": "EstimatedBilled",
            "summarizeBy": "sum"
          },
          {
            "name": "Hours",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "27844ab0-8847-42b9-93f9-5d66e6a803a4",
            "sourceColumn": "Hours",
            "summarizeBy": "sum"
          },
          {
            "name": "Billed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e1553cdd-9095-44ef-aa22-03bbde9070e9",
            "sourceColumn": "Billed",
            "summarizeBy": "sum"
          },
          {
            "name": "Job_StartDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "01d29dc8-e1f8-44b6-8baa-fc7ae5555fa1",
            "sourceColumn": "Job_StartDate",
            "summarizeBy": "none"
          },
          {
            "name": "DateTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "20f1073e-9d94-47bc-8346-cbd82a4851a9",
            "sourceColumn": "DateTime",
            "summarizeBy": "none"
          },
          {
            "name": "Service ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4192113d-6ec2-40a8-812c-2397712eba32",
            "sourceColumn": "Service ID",
            "summarizeBy": "none"
          },
          {
            "name": "Site_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dc47b609-f996-424d-aab2-2df13c94078e",
            "sourceColumn": "Site_Name",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b03ecb2e-c17e-4d5a-a731-c7e7a1950891",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Service_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d88a6b48-9d92-4857-ba0c-65baea0a8bc5",
            "sourceColumn": "Service_type",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a32dddc6-dfe2-4582-b330-2d533817bbc7",
            "sourceColumn": "City",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "414f0fec-5f37-45f8-99cf-618a139465dd",
        "partitions": [
          {
            "name": "Fact - Care Hires Data",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Folder.Files(Data_Source),",
                "    #\"C:\\Users\\kporw\\Desktop\\PORTFOLIO\\Care Hours - Data\\_Fact - Care Hires Data csv\" = Source{[#\"Folder Path\"=\"C:\\Users\\kporw\\Desktop\\PORTFOLIO\\Care Hours - Data\\\",Name=\"Fact - Care Hires Data.csv\"]}[Content],",
                "    #\"Imported CSV\" = Csv.Document(#\"C:\\Users\\kporw\\Desktop\\PORTFOLIO\\Care Hours - Data\\_Fact - Care Hires Data csv\",[Delimiter=\",\", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Id\", Int64.Type}, {\"Status\", type text}, {\"Agency\", type text}, {\"Site_Short\", type text}, {\"Site_Name\", type text}, {\"WorkerType\", type text}, {\"EstimatedHours\", Int64.Type}, {\"EstimatedBilled\", type number}, {\"Hours\", Int64.Type}, {\"Billed\", type number}, {\"Job_StartDate\", type date}, {\"DateTime\", type text}, {\"Service ID\", Int64.Type}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",\"T\",\"\",Replacer.ReplaceText,{\"DateTime\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"Z\",\"\",Replacer.ReplaceText,{\"DateTime\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",\" \",\"\",Replacer.ReplaceText,{\"DateTime\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Replaced Value2\",{{\"DateTime\", type time}, {\"Service ID\", type text}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type1\", each true),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Filtered Rows\", {\"Service ID\"}, #\"Dim - Site Master\", {\"Service ID\"}, \"Dim - Site Master\", JoinKind.LeftOuter),",
                "    #\"Expanded Dim - Site Master1\" = Table.ExpandTableColumn(#\"Merged Queries\", \"Dim - Site Master\", {\"Region\", \"Service_type\", \"City\"}, {\"Region\", \"Service_type\", \"City\"})",
                "in",
                "    #\"Expanded Dim - Site Master1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim - Site Master",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "StateOrProvince",
            "dataType": "string",
            "lineageTag": "9c6b4e0b-41cd-4e53-ad17-a151d00ba907",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9a9c790c-182a-4225-8e3d-b38a71a333b3",
            "sourceColumn": "email",
            "summarizeBy": "none"
          },
          {
            "name": "Service_Short",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c7d2c79d-825e-4ac1-b5fa-cff47451c3f2",
            "sourceColumn": "Service_Short",
            "summarizeBy": "none"
          },
          {
            "name": "Service ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eee3983c-9224-421b-ac1a-05f0d5257cea",
            "sourceColumn": "Service ID",
            "summarizeBy": "none"
          },
          {
            "name": "Company",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4721f202-ddb8-449d-8771-5660a5396de7",
            "sourceColumn": "Company",
            "summarizeBy": "none"
          },
          {
            "name": "OpsManager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9c202477-d9f4-42c4-b7cf-1e2de5e22d78",
            "sourceColumn": "OpsManager",
            "summarizeBy": "none"
          },
          {
            "name": "SiteManager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b16f0138-0150-4ea4-85b2-547f56ea2df2",
            "sourceColumn": "SiteManager",
            "summarizeBy": "none"
          },
          {
            "name": "Service_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "862f9336-c500-4b0d-91d3-9c4379d1c160",
            "sourceColumn": "Service_type",
            "summarizeBy": "none"
          },
          {
            "name": "Service_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2232c2d9-a087-4c58-9170-3f52d255cf60",
            "sourceColumn": "Service_Name",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "da74a88e-a05b-4350-8b6e-331cad3a3049",
            "sourceColumn": "City",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d4e8ee18-5b58-43bb-9919-d48159c8f73d",
        "partitions": [
          {
            "name": "Dim - Site Master",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Folder.Files(Data_Source),",
                "    #\"C:\\Users\\kporw\\Desktop\\PORTFOLIO\\Care Hours - Data\\_DIM - Site Master csv\" = Source{[#\"Folder Path\"=\"C:\\Users\\kporw\\Desktop\\PORTFOLIO\\Care Hours - Data\\\",Name=\"DIM - Site Master.csv\"]}[Content],",
                "    #\"Imported CSV\" = Csv.Document(#\"C:\\Users\\kporw\\Desktop\\PORTFOLIO\\Care Hours - Data\\_DIM - Site Master csv\",[Delimiter=\",\", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Region\", type text}, {\"Company\", type text}, {\"OpsManager\", type text}, {\"email\", type text}, {\"Service_type\", type text}, {\"SiteManager\", type text}, {\"Service_Short\", type text}, {\"Service_Name\", type text}, {\"Service ID\", Int64.Type}, {\"City\", type text}}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Promoted Headers\", {\"Service ID\"}),",
                "    #\"Removed Duplicates2\" = Table.Distinct(#\"Removed Duplicates\", {\"Service_Name\"})",
                "in",
                "    #\"Removed Duplicates2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim - Date",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "isKey": true,
            "lineageTag": "f436d1b5-06b0-49d7-b2c5-25af3609e927",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "32b54765-57e1-43f0-91ee-3d34f727e347",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Start of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "eae9b61a-a105-45f4-8606-76cb35cd5bbd",
            "sourceColumn": "Start of Year",
            "summarizeBy": "none"
          },
          {
            "name": "End of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "62eb6ee0-bfca-4ffb-9c6d-1d3a667838b9",
            "sourceColumn": "End of Year",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "084a0c16-dae2-4379-b9f8-e77ff17db3a6",
            "sourceColumn": "Month",
            "summarizeBy": "sum"
          },
          {
            "name": "Start of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "6eabf6b1-408f-461a-9c9a-18ac124e7d07",
            "sourceColumn": "Start of Month",
            "summarizeBy": "none"
          },
          {
            "name": "End of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "9493058c-40a6-4f75-a99f-54e016dbeb1d",
            "sourceColumn": "End of Month",
            "summarizeBy": "none"
          },
          {
            "name": "Days in Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0cd04ef2-c636-4938-b26a-d13bc4ed1261",
            "sourceColumn": "Days in Month",
            "summarizeBy": "sum"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "52b01683-10fe-4db7-b8ce-4a9148910f08",
            "sourceColumn": "Day",
            "summarizeBy": "sum"
          },
          {
            "name": "Day Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3cc78753-d74f-454f-a6d8-a433426b1d6e",
            "sourceColumn": "Day Name",
            "summarizeBy": "none"
          },
          {
            "name": "Day of Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c8c0c51d-579e-407c-ae6f-964c606787c2",
            "sourceColumn": "Day of Week",
            "summarizeBy": "sum"
          },
          {
            "name": "Day of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "98d05b34-a304-4016-a752-64da12ab5a52",
            "sourceColumn": "Day of Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0f11c766-30a2-4be1-86c3-b1fa4bb91220",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "35d4ef9b-1e57-47f6-9237-d45a6590267f",
            "sourceColumn": "Quarter",
            "summarizeBy": "sum"
          },
          {
            "name": "Start of Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f2807c35-d2c4-4614-af04-c1cbff2f54ec",
            "sourceColumn": "Start of Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "End of Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f8caef9f-b4b8-4d51-b6f5-8500a579405f",
            "sourceColumn": "End of Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Week of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1ef34f95-4e6f-4d75-bd17-f0ae4476ba71",
            "sourceColumn": "Week of Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Week of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "48bf72b0-533e-4181-bdeb-8c3306a2daed",
            "sourceColumn": "Week of Month",
            "summarizeBy": "sum"
          },
          {
            "name": "Start of Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "5cf497b3-0e72-4438-9c1b-863d5d1d9376",
            "sourceColumn": "Start of Week",
            "summarizeBy": "none"
          },
          {
            "name": "End of Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "486581d8-c61c-4327-b92b-7c1a92e708de",
            "sourceColumn": "End of Week",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bbe14f47-b30f-4d17-a0db-1360939a94a6",
            "sourceColumn": "Fiscal Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "16617a72-910e-4cf7-88dd-9fedbde1fafd",
            "sourceColumn": "Fiscal Quarter",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "681558a0-2353-4682-acac-c29c118a89c7",
            "sourceColumn": "Fiscal Month",
            "summarizeBy": "sum"
          },
          {
            "name": "Day Offset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f263ee98-db30-4416-8b5e-9c9724590ac1",
            "sourceColumn": "Day Offset",
            "summarizeBy": "sum"
          },
          {
            "name": "Month Offset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7c2d9400-375b-4bcf-b03b-abd4013c227b",
            "sourceColumn": "Month Offset",
            "summarizeBy": "sum"
          },
          {
            "name": "Year Offset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6a3e3a95-537a-4e86-ab1f-ec38ed7bf42b",
            "sourceColumn": "Year Offset",
            "summarizeBy": "sum"
          },
          {
            "name": "Quarter Offset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "75f869d2-54a6-4168-bd89-1670533938b6",
            "sourceColumn": "Quarter Offset",
            "summarizeBy": "sum"
          },
          {
            "name": "Year-Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mmm yyyy",
            "isNullable": false,
            "lineageTag": "eb2640d7-752d-4bea-ace6-5082cde08ea5",
            "sourceColumn": "Year-Month",
            "summarizeBy": "none"
          },
          {
            "name": "Year-Month Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e69c31d1-5630-40d6-ab33-f39c27b3501e",
            "sourceColumn": "Year-Month Code",
            "summarizeBy": "count"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "3df4bec7-dd0f-4b1a-bf26-09e51837e1ed",
        "partitions": [
          {
            "name": "Dim - Date",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "        Source = Folder.Files(Data_Source),",
                "    #\"C:\\Users\\kporw\\Desktop\\PORTFOLIO\\Care Hours - Data\\_DIM - Date csv\" = Source{[#\"Folder Path\"=\"C:\\Users\\kporw\\Desktop\\PORTFOLIO\\Care Hours - Data\\\",Name=\"DIM - Date.csv\"]}[Content],",
                "    #\"Imported CSV\" = Csv.Document(#\"C:\\Users\\kporw\\Desktop\\PORTFOLIO\\Care Hours - Data\\_DIM - Date csv\",[Delimiter=\",\", Columns=31, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Date\", type date}, {\"Year\", Int64.Type}, {\"Start of Year\", type date}, {\"End of Year\", type date}, {\"Month\", Int64.Type}, {\"Start of Month\", type date}, {\"End of Month\", type date}, {\"Days in Month\", Int64.Type}, {\"Day\", Int64.Type}, {\"Day Name\", type text}, {\"Day of Week\", Int64.Type}, {\"Day of Year\", Int64.Type}, {\"Month Name\", type text}, {\"Quarter\", Int64.Type}, {\"Start of Quarter\", type date}, {\"End of Quarter\", type date}, {\"Week of Year\", Int64.Type}, {\"Week of Month\", Int64.Type}, {\"Start of Week\", type date}, {\"End of Week\", type date}, {\"Fiscal Year\", Int64.Type}, {\"Fiscal Quarter\", Int64.Type}, {\"Fiscal Month\", Int64.Type}, {\"Day Offset\", Int64.Type}, {\"Month Offset\", Int64.Type}, {\"Year Offset\", Int64.Type}, {\"Quarter Offset\", Int64.Type}, {\"Year-Month\", type date}, {\"Year-Month Code\", Int64.Type}, {\"Within Fact Table date Range\", type logical}, {\"Commissioned Hours daily value\", type number}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Within Fact Table date Range\", \"Commissioned Hours daily value\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Measures_Table",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "lineageTag": "a12f9442-8604-41af-b348-05fdfd18682b",
        "measures": [
          {
            "name": "Period_Card",
            "displayFolder": "Data_Measures",
            "expression": [
              "",
              "VAR A = FORMAT(FIRSTDATE('Dim - Date'[Date]),\"DD MMM YYYY\")",
              "VAR B = FORMAT(LASTDATE('Dim - Date'[Date]),\"DD MMM YYYY\")",
              "VAR Period_Card = A&\" - \"&B",
              "RETURN",
              "Period_Card"
            ],
            "lineageTag": "d97f4cd2-79ff-49e7-82cb-22008e034f81"
          },
          {
            "name": "Commisioned_Hours",
            "displayFolder": "Contracted_Measures",
            "expression": "SUM('Fact - Rota'[SU Hours])",
            "formatString": "#,0",
            "lineageTag": "2d305ea7-2656-4e9e-80ee-1116724a8055"
          },
          {
            "name": "Timesheet_Care_Hours",
            "displayFolder": "Contracted_Measures",
            "expression": [
              "",
              "VAR Care_Hours = ",
              "    CALCULATE(",
              "       SUM('Fact - Timesheet-updated'[Commissioned Hours]),",
              "       'Fact - Timesheet-updated'[Department] = \"Care\",",
              "       'Fact - Timesheet-updated'[Pay_Code] IN {\"Early In\", \"Enhanced Pay\", \"Late Out\", \"L-In OK\", \"Sleep in\", \"Overtime\", \"Worked Unscheduled\", \"WRK\"},",
              "       'Fact - Timesheet-updated'[Pay_Category] IN {\"Hol1.5\", \"Hol2.0\", \"OT 1.0\", \"Sleepin\", \"Overtime\", \"Reg\"}",
              "    )",
              "RETURN COALESCE(Care_Hours,0)"
            ],
            "formatString": "#,0",
            "lineageTag": "6f659820-0d38-4d77-94b2-b738f9661026"
          },
          {
            "name": "Timesheet_Commisioned_Hours",
            "displayFolder": "Agency_Measures",
            "expression": [
              "",
              "IF(ISBLANK(",
              "CALCULATE(",
              "    SUM('Fact - Timesheet-updated'[Commissioned Hours]),",
              "    FILTER",
              "        ('Fact - Timesheet-updated',",
              "        'Fact - Timesheet-updated'[Department] = \"Agency\")",
              "        )",
              "),0,",
              "",
              "CALCULATE(",
              "    SUM('Fact - Timesheet-updated'[Commissioned Hours]),",
              "    FILTER",
              "        ('Fact - Timesheet-updated',",
              "        'Fact - Timesheet-updated'[Department]= \"Agency\")",
              "    )",
              "",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "24e07d31-33fb-4f2a-b5de-88b04ca43797"
          },
          {
            "name": "Managers_OverTime",
            "displayFolder": "Contracted_Measures",
            "expression": [
              "CALCULATE(",
              "    SUM('Fact - Timesheet-updated'[Commissioned Hours]),",
              "   ('Fact - Timesheet-updated'[Department] = \"Management\" ||",
              "    'Fact - Timesheet-updated'[Department] = \"Management (DM)\" ||",
              "    'Fact - Timesheet-updated'[Department] = \"Management (Service Manager)\"),",
              "",
              "   ('Fact - Timesheet-updated'[Pay_Code] = \"Early In\" || ",
              "    'Fact - Timesheet-updated'[Pay_Code] = \"Enhanced Pay\" ||",
              "    'Fact - Timesheet-updated'[Pay_Code] = \"Late Out\" ||",
              "    'Fact - Timesheet-updated'[Pay_Code] = \"L-In OK\" ||",
              "    'Fact - Timesheet-updated'[Pay_Code] = \"Overtime\" ||",
              "    'Fact - Timesheet-updated'[Pay_Code] = \"Worked Unscheduled\" ||",
              "    'Fact - Timesheet-updated'[Pay_Code] = \"WRK\" ),",
              "",
              "   ('Fact - Timesheet-updated'[Pay_Category] = \"OT 1.0\" ||",
              "    'Fact - Timesheet-updated'[Pay_Category] = \"Overtime\")",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "c1917ccc-786f-4efb-bf9a-2c0e5ba610e8"
          },
          {
            "name": "Care_Hire_Hours_Allocated",
            "displayFolder": "Agency_Measures",
            "expression": "CALCULATE(SUM('Fact - Care Hires Data'[EstimatedHours]),'Fact - Care Hires Data'[Status] = \"Allocated\")",
            "formatString": "#,0",
            "lineageTag": "fa10fda4-dda8-495e-9c7f-273ba10bf651"
          },
          {
            "name": "Care_Hire_Hours_Completed",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Agency_Measures",
            "expression": "CALCULATE(SUM('Fact - Care Hires Data'[EstimatedBilled]),'Fact - Care Hires Data'[Status] = \"Completed\")",
            "formatString": "#,0",
            "lineageTag": "e53124c9-9e4f-43ea-8119-f86a575a932e"
          },
          {
            "name": "Care_Hires_Hours_Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Agency_Measures",
            "expression": [
              "",
              "IF(",
              "    ISBLANK([Care_Hire_Hours_Allocated]),0,[Care_Hire_Hours_Allocated]",
              ")",
              "    +",
              "IF(",
              "    ISBLANK([Care_Hire_Hours_Completed]),0,[Care_Hire_Hours_Completed]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "facca444-0307-4a9f-befc-b0e24a75894e"
          },
          {
            "name": "Care_Hires_Adjusted",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Agency_Measures",
            "expression": "IF([Timesheet_Commisioned_Hours] >= [Care_Hires_Hours_Total],\"0\",[Care_Hires_Hours_Total] - [Timesheet_Commisioned_Hours])",
            "formatString": "#,0",
            "lineageTag": "2c26815e-c61e-4d5b-a8a7-2894a1dd639c"
          },
          {
            "name": "Total_Care_Hours",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Contracted_Measures",
            "expression": [
              "",
              "VAR A = [Timesheet_Commisioned_Hours]",
              "VAR B = [Timesheet_Care_Hours]",
              "VAR C = [Care_Hires_Adjusted]",
              "VAR D = [Managers_OverTime]",
              "",
              "VAR Care_Hours = B + D",
              "RETURN Care_Hours"
            ],
            "formatString": "#,0",
            "lineageTag": "bb21ad97-53aa-4546-b46b-6462fe5ea4b9"
          },
          {
            "name": "Contracted_Hours_vs_Actual_Hours",
            "displayFolder": "Variance_Measures",
            "expression": [
              "",
              "VAR A = [Total_Care_Hours] - [Commisioned_Hours]",
              "",
              "VAR FORMATTED = ",
              "    IF(",
              "        A >= 0, ",
              "        FORMAT(A, \"#,## h\"), ",
              "        \"(\" & FORMAT(ABS(A), \"#,##\") & \") h\"",
              "    )",
              "",
              "RETURN FORMATTED"
            ],
            "lineageTag": "5a8521b9-2d8b-4f0c-8596-b7cf032bc83f"
          },
          {
            "name": "Hours_Variance_Percentage_for_Contracted_Display",
            "displayFolder": "Variance_Measures",
            "expression": [
              "",
              "VAR A = [Total_Care_Hours] - [Commisioned_Hours]",
              "VAR B = A / [Commisioned_Hours] * 100",
              "",
              "RETURN ",
              "    IF(",
              "        [Commisioned_Hours] = 0,",
              "        FORMAT(B, \"0.0\") & \"%\",  -- Display 0 as 0.0%",
              "        IF(",
              "            B < 0, ",
              "            \"(\" & FORMAT(ABS(B), \"0.0\") & \") %\",  -- Format negative numbers with parentheses",
              "            FORMAT(B, \"0.0\") & \"%\"  -- Format positive numbers normally",
              "        )",
              "    )"
            ],
            "lineageTag": "de079acc-a9f5-451b-987a-7de4bb30f057"
          },
          {
            "name": "Commisioned_hours_daily",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Contracted_Measures",
            "expression": "SUM('Fact - Rota'[SU_Hours_per_day])",
            "lineageTag": "084a2b26-bcd4-42d6-93c9-9cf72657e4b0"
          },
          {
            "name": "Unauthorised_by_manager",
            "displayFolder": "Agency_Measures",
            "expression": [
              "",
              "VAR A = CALCULATE(",
              "    COUNT('Fact - Timesheet-updated'[Authorised_by_Manager]),",
              "    FILTER('Fact - Timesheet-updated',",
              "    'Fact - Timesheet-updated'[Authorised_by_Manager] = \"No\")",
              ")",
              "VAR B = IF(A > 0, A, 0)",
              "RETURN",
              "B"
            ],
            "formatString": "0",
            "lineageTag": "3e2e96b4-523d-494a-8618-e1cccd7c56fe"
          },
          {
            "name": "Total_Timesheets",
            "displayFolder": "Agency_Measures",
            "expression": "COUNT('Fact - Timesheet-updated'[Authorised_by_Employee])",
            "formatString": "0",
            "lineageTag": "a48aef94-bbf4-4b32-b0a3-eb01db4fbabb"
          },
          {
            "name": "Unauthorised_%",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Agency_Measures",
            "expression": "DIVIDE([Unauthorised_by_manager],[Total_Timesheets])",
            "lineageTag": "f0fee371-4318-4b51-b5a6-75a24fe6ecdc"
          },
          {
            "name": "Agency Cost",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Agency_Measures",
            "expression": "CALCULATE(SUM('Fact - Care Hires Data'[Billed]),'Fact - Timesheet-updated'[Region])",
            "lineageTag": "699c7ee3-d428-4cee-8b14-535676a450be"
          },
          {
            "name": "Managers_Overtime_Hours",
            "displayFolder": "Table_Total_Hours_Monthly",
            "expression": [
              "",
              "VAR OvertimeHours =",
              "    CALCULATE(",
              "        SUM('Fact - Timesheet-updated'[Commissioned Hours]),",
              "        'Fact - Timesheet-updated'[Department] IN {\"Management\", \"Management (DM)\", \"Management (Service Manager)\"},",
              "        'Fact - Timesheet-updated'[Pay_Code] = \"Overtime\",",
              "        'Fact - Timesheet-updated'[Pay_Category] = \"Overtime\"",
              "    )",
              "    ",
              "RETURN",
              "    COALESCE(OvertimeHours,0)"
            ],
            "formatString": "0.00",
            "lineageTag": "e5ae214e-bf61-4a08-be13-06b2ff9dfb31"
          },
          {
            "name": "Timesheet_Contracted_Hours",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Table_Total_Hours_Monthly",
            "expression": [
              "",
              "VAR ContractedHours =",
              "    CALCULATE(",
              "        SUM('Fact - Timesheet-updated'[Commissioned Hours]),",
              "        'Fact - Timesheet-updated'[Department] = \"Agency\"",
              "    )",
              "RETURN",
              "    COALESCE(ContractedHours,0)"
            ],
            "lineageTag": "19a7de11-fffa-4909-803f-03db84753c33"
          },
          {
            "name": "Other_Hours",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Table_Total_Hours_Monthly",
            "expression": [
              "",
              "VAR OtherHours = CALCULATE(",
              "         SUM('Fact - Timesheet-updated'[Other]),",
              "         'Fact - Timesheet-updated'[Department] = \"Care\",",
              "         'Fact - Timesheet-updated'[Pay_Code] IN {\"Suspension PaidReg\", \"Antenatal Appointment\", \"Parental Leave\", \"Compassionate leave\",\"Accident in Workplace (PAID)\", \"SSP\", \"Keeping in touch (KIT) Days\", \"Authorised Absence\", \"Jury\"},",
              "         'Fact - Timesheet-updated'[Pay_Category] IN {\"Reg\", \"Parental Pay\", \"Overtime\", \"SSP\", \"Other\", \"Jury\"}",
              "     )",
              "",
              "RETURN",
              "    COALESCE(OtherHours, 0)"
            ],
            "lineageTag": "e6dbd59d-f454-42af-ada8-be92146e633e"
          },
          {
            "name": "Unpaid_Hours",
            "displayFolder": "Table_Total_Hours_Monthly",
            "expression": [
              "",
              "VAR UnpaidHours = CALCULATE(",
              "         SUM('Fact - Timesheet-updated'[Other]),",
              "         'Fact - Timesheet-updated'[Department] = \"Care\",",
              "         'Fact - Timesheet-updated'[Pay_Code] IN {\"E-In Unpaid\", \"Late in Unpaid\", \"L-Out Unpaid\", \"Unauthorised Absence\", \"E-Out Unpaid\",\"Unpaid E-Out\", \"Unpaid Holiday\", \"Unpaid L-In\", \"Unpaid Late Out\", \"Unpaid Early IN\", \"Unpaid Sickness Absence\", \"Suspension Unpaid\", \"Hospital Appointment\" },",
              "        'Fact - Timesheet-updated'[Pay_Category] IN {\"Unpaid\", \"Reg\", \"Ot1.0\", \"OT 1.0\", \"Unpaid Sickness Absence\", \"Overtime\"}",
              "    )",
              "RETURN",
              "    COALESCE(UnpaidHours, 0)"
            ],
            "formatString": "0",
            "lineageTag": "a9fa5425-5edc-4b4a-bcf5-9c532ef83348"
          },
          {
            "name": "Sickness_Hours",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Table_Total_Hours_Monthly",
            "expression": [
              "",
              "VAR SicknessHours = CALCULATE(",
              "         SUM('Fact - Timesheet-updated'[Other]),",
              "         'Fact - Timesheet-updated'[Department] = \"Care\",",
              "         'Fact - Timesheet-updated'[Pay_Code] IN {\"Sickness (Unpaid)\", \"Sickness (Paid) DirectorDis\", \"Sick Offset\", \"Sickness\"},",
              "         'Fact - Timesheet-updated'[Pay_Category] IN {\"Sickness (Unpaid)\", \"Reg\", \"Sick Offset\", \"Sick Pay Unpaid\"}",
              "    )",
              "RETURN",
              "    COALESCE(SicknessHours, 0)"
            ],
            "lineageTag": "7c037484-e84a-456c-9128-8f42146cbb36"
          },
          {
            "name": "Annual_Leave_Payout",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Table_Total_Hours_Monthly",
            "expression": [
              "",
              "VAR Payout =",
              "    CALCULATE(",
              "         SUM('Fact - Timesheet-updated'[Other]),",
              "         'Fact - Timesheet-updated'[Department] = \"Care\",",
              "         'Fact - Timesheet-updated'[Pay_Code] = \"Annual Leave Payout\",",
              "         'Fact - Timesheet-updated'[Pay_Category] = \"Annual Leave Payout\"",
              "    )",
              "RETURN",
              "    COALESCE(Payout, 0)"
            ],
            "lineageTag": "e0c5c6d3-1f58-4dfe-82aa-b521483ee27b"
          },
          {
            "name": "Holiday_Hours",
            "displayFolder": "Table_Total_Hours_Monthly",
            "expression": [
              "",
              "VAR Holiday =",
              "    CALCULATE(",
              "         SUM('Fact - Timesheet-updated'[Other]),",
              "         'Fact - Timesheet-updated'[Department] = \"Care\",",
              "         'Fact - Timesheet-updated'[Pay_Code] = \"Holiday\",",
              "         'Fact - Timesheet-updated'[Pay_Category] IN {\"Vacation\", \"Overtime\"}",
              "    )",
              "RETURN",
              "    COALESCE(Holiday, 0)"
            ],
            "formatString": "0.00",
            "lineageTag": "7eac8362-544a-4797-a357-347a98b1664f"
          },
          {
            "name": "Staff_Normal_Hours",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Table_Total_Hours_Monthly",
            "expression": [
              "",
              "VAR Normal_Hours =",
              "    CALCULATE(",
              "        SUM('Fact - Timesheet-updated'[Commissioned Hours]),",
              "        'Fact - Timesheet-updated'[Department] = \"Care\",",
              "        'Fact - Timesheet-updated'[Pay_Code] IN {\"Early In\", \"Late Out\", \"L-In OK\", \"Worked Unscheduled\", \"WRK\"},",
              "        'Fact - Timesheet-updated'[Pay_Category]  = \"Reg\"",
              "    )",
              "RETURN",
              "    COALESCE(Normal_Hours, 0)"
            ],
            "lineageTag": "17ae00f4-549f-43c0-ba5b-821037538cc1"
          },
          {
            "name": "Training_Hours",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Table_Total_Hours_Monthly",
            "expression": [
              "",
              "VAR Training =",
              "    CALCULATE(",
              "        SUM('Fact - Timesheet-updated'[Commissioned Hours]),",
              "        'Fact - Timesheet-updated'[Department] = \"Care\",",
              "        'Fact - Timesheet-updated'[Pay_Code] = \"Training\",",
              "        'Fact - Timesheet-updated'[Pay_Category] IN {\"Reg\", \"Overtime\", \"OT 1.0\"}",
              "    )",
              "RETURN",
              "    COALESCE(Training, 0)"
            ],
            "lineageTag": "c64503c9-1f6b-45d6-b629-baf2f3558700"
          },
          {
            "name": "Variance_for_Monthly_RLS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Table_Total_Hours_Monthly",
            "expression": [
              "",
              "VAR UserFullAccess =",
              "    COUNTROWS(ALL('Dim - Site Master')) = COUNTROWS(ALLSELECTED('Dim - Site Master'))",
              "",
              "RETURN",
              "IF(UserFullAccess,0,[Variance_for_Monthly]",
              ")"
            ],
            "lineageTag": "ff11696e-6bd4-4946-a5e4-6687d4420b01"
          },
          {
            "name": "Variance_for_Monthly",
            "displayFolder": "Table_Total_Hours_Monthly",
            "expression": [
              "",
              "VAR A = [Total_Care_Hours] - [Commisioned_Hours]",
              "",
              "VAR FormattedValue =",
              "    IF(",
              "        A >= 0,",
              "        FORMAT(A, \"#,## h\"),",
              "        \"(\" & FORMAT(ABS(A), \"#,##\") & \") h\"",
              "    )",
              "",
              "RETURN",
              "IF(",
              "    OR(",
              "        ISFILTERED('Dim - Site Master'[Region]),",
              "        OR(",
              "            ISFILTERED('Dim - Site Master'[Service_Name]),",
              "            ISFILTERED('Dim - Site Master'[Service_type])",
              "        )",
              "    ),",
              "    \"\",",
              "    FormattedValue",
              ")"
            ],
            "lineageTag": "9cb5866f-7908-44d7-b3b2-753f4df4e5d6"
          },
          {
            "name": "Table_Values",
            "displayFolder": "Table_Total_Hours_Monthly",
            "expression": [
              "",
              "SWITCH(",
              "    SELECTEDVALUE('Table_Monthly_Total_Hours'[Measures]),",
              "     \"Staff Normal Hours\", [Staff_Normal_Hours],",
              "     \"Staff Overtime Hours\" , [Staff_Overtime_Hours],",
              "     \"Agency Hours\",[Timesheet_Agency_Hours],",
              "     \"Care Hires Adj.\", [Care_Hires_Adjusted] , ",
              "     \"\", \"\" ,",
              "     \"Total Delivered Hours\", [Total_Care_Hours] , ",
              "     \"Managers Hours (excl. Overtime)\", [Managers_Hours_excl.Overtime] ,",
              "     \"Training Hours\", [Training_Hours] ,",
              "     \"Holiday Hours\", [Holiday_Hours],",
              "     \"Annual Leave Payout\", [Annual_Leave_Payout],",
              "      \"Sickness Hours\", [Sickness_Hours], ",
              "      \"Unpaid Hours\", [Unpaid_Hours], ",
              "      \"Other Hours\", [Other_Hours],",
              "      \" \", \" \" ,",
              "      \" Total Hours\", [Total_Hours]    ",
              "        )"
            ],
            "formatString": "#,0",
            "lineageTag": "e8ac3ea6-2315-4d79-b0b6-70235f8075f0"
          },
          {
            "name": "Staff_Overtime_Hours",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Table_Total_Hours_Monthly",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM('Fact - Timesheet-updated'[Commissioned Hours]),",
              "    'Fact - Timesheet-updated'[Department] = \"Care\",",
              "    'Fact - Timesheet-updated'[Pay_Code] IN {\"Early In\", \"Late Out\", \"L-In OK\", \"Overtime\", \"Worked Unscheduled\", \"WRK\"},",
              "    'Fact - Timesheet-updated'[Pay_Category] IN {\"OT 1.0\", \"Overtime\"}",
              ")"
            ],
            "lineageTag": "89f13721-0104-4c39-9819-9211d218cb33"
          },
          {
            "name": "Timesheet_Agency_Hours",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Table_Total_Hours_Monthly",
            "expression": [
              "",
              "VAR AgencyHours =",
              "    CALCULATE(",
              "        SUM('Fact - Timesheet-updated'[Commissioned Hours]),",
              "        'Fact - Timesheet-updated'[Department] = \"Agency\"",
              "    )",
              "RETURN",
              "    COALESCE(AgencyHours, 0)"
            ],
            "lineageTag": "94dc7979-0f50-402d-ab70-82d543143b4e"
          },
          {
            "name": "Contracted_Hours_for_Monthly",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Table_Total_Hours_Monthly",
            "expression": [
              "",
              "IF(",
              "    OR(",
              "        ISFILTERED('Dim - Site Master'[Region]),",
              "        OR(",
              "            ISFILTERED('Dim - Site Master'[Service_Name]),",
              "            ISFILTERED('Dim - Site Master'[Service_type])",
              "        )",
              "    ),",
              "    \"\",",
              "    SUM('Fact - Rota'[Contracted_Hours_daily]",
              "))"
            ],
            "lineageTag": "b23d59e0-3bbd-440e-9f09-a7e600612d97"
          },
          {
            "name": "Contracted_Hours_for_Monthly_RLS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Table_Total_Hours_Monthly",
            "expression": [
              "",
              "VAR UserFullAccess = COUNTROWS(ALL('Dim - Site Master')) = CALCULATE(COUNTROWS('Dim - Site Master'),ALLSELECTED('Dim - Site Master'))",
              "",
              "RETURN",
              "IF(",
              "    UserFullAccess, 0 , [Contracted_Hours_for_Monthly])"
            ],
            "lineageTag": "1658e935-a7c1-4e6d-95e3-2076bacaa142"
          },
          {
            "name": "Managers_Hours_excl.Overtime",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Table_Total_Hours_Monthly",
            "expression": [
              "",
              "VAR Hours =",
              "    CALCULATE(",
              "        SUM('Fact - Timesheet-updated'[Commissioned Hours]),",
              "        'Fact - Timesheet-updated'[Department] IN {\"Management\", \"Management (DM)\", \"Management (Service Manager)\"},",
              "        'Fact - Timesheet-updated'[Pay_Code] IN {\"Early In\", \"Enhanced Pay\", \"Late Out\", \"L-In OK\", \"Worked Unscheduled\", \"WRK\"},",
              "        'Fact - Timesheet-updated'[Pay_Category] = \"OT 1.0\"",
              "    )",
              "    ",
              "RETURN",
              "    COALESCE(Hours,0)"
            ],
            "formatString": "0",
            "lineageTag": "0569020e-198d-4878-9a00-96db4a211be2"
          },
          {
            "name": "Total_Hours",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Table_Total_Hours_Monthly",
            "expression": [
              "",
              "[Staff_Normal_Hours] +",
              "[Staff_Overtime_Hours] + ",
              "[Timesheet_Agency_Hours] + ",
              "[Care_Hires_Adjusted] +  ",
              "[Total_Care_Hours] + ",
              "[Managers_Hours_excl.Overtime] + ",
              "[Training_Hours] + ",
              "[Holiday_Hours] + ",
              "[Annual_Leave_Payout] + ",
              "[Sickness_Hours] + ",
              "[Unpaid_Hours] +  ",
              "[Other_Hours]"
            ],
            "lineageTag": "e7a8ee4b-c750-403c-b99c-32542332d335"
          }
        ],
        "partitions": [
          {
            "name": "Measures_Table",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"}),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Removed Columns\", \"Index\", 1, 1, Int64.Type),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Added Index\",{\"Index\"})",
                "in",
                "    #\"Removed Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact - Timesheet-updated",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Department",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6e43f9d2-0ac5-46c3-9e16-141e28ca1a2c",
            "sourceColumn": "Department",
            "summarizeBy": "none"
          },
          {
            "name": "Job",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1cc09a0d-0f7b-4e66-9f6f-48a044c7b1df",
            "sourceColumn": "Job",
            "summarizeBy": "none"
          },
          {
            "name": "Hours",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.00",
            "lineageTag": "f20bcf5d-e8f9-4afb-bd61-125a5421828c",
            "sourceColumn": "Hours",
            "summarizeBy": "sum"
          },
          {
            "name": "Other",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.00",
            "lineageTag": "379472da-fd4e-4796-819d-9bcc19cf27ab",
            "sourceColumn": "Other",
            "summarizeBy": "sum"
          },
          {
            "name": "Commissioned Hours",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.00",
            "lineageTag": "cdef58ee-2106-47a4-a834-0ffc0fba3fe5",
            "sourceColumn": "Commissioned Hours",
            "summarizeBy": "sum"
          },
          {
            "name": "Service ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2a7c994a-f0a0-4e3a-9c09-7a1cb2cb23a8",
            "sourceColumn": "Service ID",
            "summarizeBy": "none"
          },
          {
            "name": "Employee_Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dbc0d03d-d684-409a-8302-14570261b7f1",
            "sourceColumn": "Employee_Number",
            "summarizeBy": "none"
          },
          {
            "name": "Employee_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c023c4b2-5081-4e4d-a3aa-aff24c3c14e6",
            "sourceColumn": "Employee_Name",
            "summarizeBy": "none"
          },
          {
            "name": "Pay_Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "60174cff-e1f5-44b9-95a6-afa316abaf09",
            "sourceColumn": "Pay_Date",
            "summarizeBy": "none"
          },
          {
            "name": "Time_in",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "9dd63815-8802-4adc-8ddb-20f2d1f4ab76",
            "sourceColumn": "Time_in",
            "summarizeBy": "none"
          },
          {
            "name": "Time Out",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "99607129-2003-421d-a309-ae4cd48835fd",
            "sourceColumn": "Time Out",
            "summarizeBy": "none"
          },
          {
            "name": "Authorised_by_Manager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "23387e6f-7d6e-4f3d-b59b-9ca2b7e30e03",
            "sourceColumn": "Authorised_by_Manager",
            "summarizeBy": "none"
          },
          {
            "name": "Authorised_by_Employee",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "74a04af5-8a6c-4c11-9781-96e7916bc254",
            "sourceColumn": "Authorised_by_Employee",
            "summarizeBy": "none"
          },
          {
            "name": "Pay_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "54a9c622-d891-4768-8bdf-cf1eac19802d",
            "sourceColumn": "Pay_Code",
            "summarizeBy": "none"
          },
          {
            "name": "Pay_Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dc8fc5f9-3a9f-4521-a8e8-8f78b7db2fbe",
            "sourceColumn": "Pay_Category",
            "summarizeBy": "none"
          },
          {
            "name": "Location_Short",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dc0bc966-8a5b-41ce-ae00-63a2f6c02b72",
            "sourceColumn": "Location_Short",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "StateOrProvince",
            "dataType": "string",
            "lineageTag": "868d5fa4-02e4-49c2-8422-885c2d3d09a9",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Service_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b9174a4a-6a9d-45dc-9cd2-0fe14f0bcc40",
            "sourceColumn": "Service_type",
            "summarizeBy": "none"
          },
          {
            "name": "Site_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d93ac895-3275-42ee-9557-305bb77c33f4",
            "sourceColumn": "Site_Name",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "City",
            "dataType": "string",
            "lineageTag": "5b994e6d-9206-47a6-a8d4-3ce1a28c06ee",
            "sourceColumn": "City",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "797df19d-d676-4ec2-983e-1d88aaf81344",
        "partitions": [
          {
            "name": "Fact - Timesheet-updated",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.NestedJoin(#\"Fact - Timesheets\", {\"Location_Short\"}, #\"Dim - Site Master\", {\"Service_Short\"}, \"Dim - Site Master\", JoinKind.LeftOuter),",
                "    #\"Merged Queries\" = Table.NestedJoin(Source, {\"Service ID\"}, #\"Dim - Site Master\", {\"Service ID\"}, \"Dim - Site Master.1\", JoinKind.LeftOuter),",
                "    #\"Expanded Dim - Site Master.1\" = Table.ExpandTableColumn(#\"Merged Queries\", \"Dim - Site Master.1\", {\"Region\", \"Service_type\", \"Service_Name\", \"City\"}, {\"Dim - Site Master.1.Region\", \"Dim - Site Master.1.Service_type\", \"Dim - Site Master.1.Service_Name\", \"Dim - Site Master.1.City\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Expanded Dim - Site Master.1\",{{\"Dim - Site Master.1.Region\", \"Region\"}, {\"Dim - Site Master.1.Service_type\", \"type\"}, {\"Dim - Site Master.1.Service_Name\", \"Site_Name\"}, {\"Dim - Site Master.1.City\", \"City\"}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Renamed Columns\",{\"Department\", \"Job\", \"Hours\", \"Other\", \"Commissioned Hours\", \"Service ID\", \"Employee_Number\", \"Employee_Name\", \"Pay_Date\", \"Time_in\", \"Time Out\", \"Authorised_by_Manager\", \"Authorised_by_Employee\", \"Pay_Code\", \"Pay_Category\", \"Location_Short\", \"Region\", \"type\", \"Site_Name\", \"City\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Other Columns\",{{\"type\", \"Service_type\"}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Renamed Columns1\", each ([Site_Name] <> null) and ([Service_type] <> \"HQ\"))",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Table_Monthly_Total_Hours",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "8ecdc28c186d4be9a3fb6304bfb3d115"
          }
        ],
        "columns": [
          {
            "name": "Measures",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNameInferred": true,
            "lineageTag": "c36eb1be-18b1-45f0-b1c3-61129fe43b6a",
            "sortByColumn": "No",
            "sourceColumn": "[Measures]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "No",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNameInferred": true,
            "lineageTag": "855a9580-e50d-43d4-b0b4-49c77d2734ca",
            "sourceColumn": "[No]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "f1559976-a953-40a5-a2e5-435d61ac472b",
        "partitions": [
          {
            "name": "Table_Monthly_Total_Hours",
            "mode": "import",
            "source": {
              "expression": [
                "DATATABLE(\"No\", INTEGER,\"Measures\", STRING,",
                "    {",
                "        {1, \"Staff Normal Hours\"},",
                "        {2, \"Staff Overtime Hours\"},",
                "        {3, \"Agency Hours\" },",
                "        {4, \"Care Hires Adj.\"},",
                "        {5, \" \"},  -- Replacing empty string with \"Blank\"",
                "        {6, \"Total Delivered Hours\"},",
                "        {7, \"Managers Hours (excl. Overtime)\" },",
                "        {8, \"Training Hours\" },",
                "        {9, \"Holiday Hours\" },",
                "        {10, \"Annual Leave Payout\" },",
                "        {11, \"Sickness Hours\" },",
                "        {12, \"Unpaid Hours\" },",
                "        {13, \"Other Hours\" },",
                "        {14, \"\" },  -- Replacing empty string with \"Blank\"",
                "        {15, \" Total Hours\"}",
                "    }",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Data_Source",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Data_Source",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "c725a4b2-9bf4-4246-bf0f-31d6d14d9156",
            "sourceColumn": "Data_Source",
            "summarizeBy": "none"
          }
        ],
        "description": "Data Source Parameter",
        "isHidden": true,
        "lineageTag": "0437cd16-9a96-4299-a498-13f9c1d7d62e",
        "partitions": [
          {
            "name": "Data_Source",
            "mode": "import",
            "queryGroup": "Parameters",
            "source": {
              "expression": "\"C:\\Users\\kporw\\Desktop\\PORTFOLIO\\Care Hours - Data\\\" meta [IsParameterQuery=true, List={\"https://zahabiltd-my.sharepoint.com/:f:/g/personal/porwol_zahabiltd_onmicrosoft_com/Eqjak0b94XdHiVA0ZrQ3cmgB1lvU9pBdnUUWMqrZiw-cDQ?e=iXIBrF\", \"C:\\Users\\kporw\\Desktop\\PORTFOLIO\\Care Hours - Data\\\"}, DefaultValue=\"C:\\Users\\kporw\\Desktop\\PORTFOLIO\\Care Hours - Data\\\", Type=\"Text\", IsParameterQueryRequired=true]",
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}